### PR TITLE
This fixes tom's PR to work with truffle 2.1.2

### LINKED ISSUE #6: unimplemented functions in OutgoingMigrationTokenInterface and IncomingMigrationTokenInterface
```function totalMigrated() external returns (uint256); ``` 
should be 
``` uint public totalMigrated; ```

same goes for newTokenAddress() 

and oldTokenAddress() in IncomingMigrationTokenInterface

### PR DESCRIPTION
**Pull request by shine2lay**
and also closes #6

---
This change is [Reviewable](https://reviewable.io/reviews/wetrustplatform/token-contracts/7)

### CODE REVIEW

**Comment by shine2lay** [comment]
this PR should also close #5 if merged

**Comment by morelazers** [comment]
Please submit this PR to `trustcoin_tests` instead of develop - that way I'll be able to see what's changed

**Comment by rmerom** [comment]
Tom,
’git pull origin sl’ might work for you even before submitting.

**Comment by morelazers** [comment]
@shine2lay closing since I've added these changes now

**Pull request closed without merging**
